Add more item search / add options, and access group search
kornelski/rust-security-framework pull request #200
Opened 2024-03-30 13:28 UTC by grahamc

2024-03-30 14:18 UTC, kornelski requested changes

2024-03-30 14:18 UTC, kornelski commented on security-framework/src/item.rs
> +        let account_name = self.account_name.as_deref().map(CFString::from);
I've just noticed that this and previous code are vulnerable to use after free. 

to_void gives a pointer to a temporary copy made by `CFString::from`. 

It should be giving a pointer to original longer lived CFString stored in self, or remove it from self and pass ownership, preventing Rust from decrementing refcount.

2024-03-31 01:07 UTC, grahamc commented on security-framework/src/item.rs
> +        let account_name = self.account_name.as_deref().map(CFString::from);
Ok! so more like `pub struct ItemSearchOptions {`, which stores the CFString directly in the struct? Can do.

2024-04-01 14:03 UTC, grahamc commented on security-framework/src/item.rs
> +        let account_name = self.account_name.as_deref().map(CFString::from);
Hey so unfortunately I'm not real confident in my ability to do this correctly. I'm not real familiar with CF or unsafe Rust. I took a look into this, but never felt good enough about what I was trying.

2024-04-02 00:22 UTC, kornelski commented on security-framework/src/item.rs
> +        let account_name = self.account_name.as_deref().map(CFString::from);
Sorry, false alarm! I've checked the implementation of `dict.add`, and it increases the reference counter. So the combo of {new string, give pointer, drop string} is valid.

2024-04-02 00:23 UTC, merged

2024-04-02 13:21 UTC, grahamc commented on security-framework/src/item.rs
> +        let account_name = self.account_name.as_deref().map(CFString::from);
🎉  thank you!